name: "Build and test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Unit tests
      run: go test -v ./...

    - name: Build
      run: make build

    - name: E2E tests
      env:
        TODO_ID: 2
      run: sh ./tests/e2e-tests.sh
